# Step C review — matches & misses

Regenerate — **do not hand-edit** the `.ipynb` JSON:

```bash
uv run python scripts/generate_notebooks.py --name step_c_review
```

**Display:** plain pandas + `walk_details` (works in Cursor). No itables/widgets required.

Compare hand gold `step_c` to predictions. Edit **CONFIG**, re-run load / filter cells.

CLI: `uv run python scripts/export_step_c_review.py`

## Config

Edit this cell, then re-run the cells below.

In [1]:
from pathlib import Path
from dataclasses import replace

from data_io import resolve
from trifecta_annotation.step_c_review import (
    StepCReviewConfig,
    load_review_frame,
    review_summary,
    save_review_frame,
    show_review,
    walk_details,
)

SCRATCH = Path(resolve('trifecta_gold')).parent
EVAL = Path(resolve('eval_reports'))

# --- knobs (change for future frames / slices) ---
CONFIG = StepCReviewConfig(
    gold_path=None,
    predictions_path=SCRATCH / 'gold_predictions.jsonl',
    output_path=EVAL / 'step_c_review.csv',
    frames=(),  # e.g. ('COOKING_CREATION',)
    tiers=(),  # e.g. ('joint', 'partial_strong', 'miss')
    fewshot_only=False,
    fewshot_levels=('yes', 'maybe'),
    min_hits=0,
    frame_ok_only=False,
)

CONFIG

StepCReviewConfig(gold_path=None, predictions_path=PosixPath('/Volumes/Extreme SSD/scratch/trifecta/gold_predictions.jsonl'), output_path=PosixPath('/Volumes/Extreme SSD/scratch/trifecta/eval/step_c_review.csv'), frames=(), tiers=(), fewshot_only=False, fewshot_levels=('yes', 'maybe'), min_hits=0, frame_ok_only=False, display_columns=('tier', 'fewshot_candidate', 'hits', 'n_fields', 'gold_frame', 'pred_frame', 'target_word', 'text_regime', 'context_snippet', 'field_hits', 'gold_fields', 'pred_fields', 'record_id'))

## Load

In [2]:
review = load_review_frame(CONFIG)
review_summary(review)

{'rows': 93,
 'tiers': {'miss': 40,
  'frame_ok_zero': 27,
  'partial': 20,
  'partial_strong': 6},
 'fewshot_flagged': 16,
 'by_frame': {'COOKING_CREATION': 31,
  'PRESERVING': 27,
  'CURE': 24,
  'INGESTION': 11}}

## Compact table

Pandas view (scrollable). Filter with the next cell if needed.

In [3]:
show_review(review, CONFIG)  # prefer_itables=True only in classic Jupyter

,tier,fewshot_candidate,hits,n_fields,gold_frame,pred_frame,target_word,text_regime,context_snippet,field_hits,gold_fields,pred_fields,record_id
0,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,Kruidnagelen,RECIPE_PRACTICE,"…oral eer ze op den Rooster gelegt worden, met eenige Kruidnagelen, en Lauwrierbladen besteken; en ze vervolgens met...",Method=✗; Process=✓; Product=✓,COOKING_CREATION_Method='besteken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method='sneeden, met eenige kruidnagelen, en lauwrierbladen besteken'; COOKING_CREATION_Process='';...",chom003huis01_01.xml__ch6__kruidnagelen
1,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,Speenvarken,RECIPE_PRACTICE,"…n heeft het geen zwarigheid: Ook moet men nooit geen Speenvarken braden, dan het geen nog zuigt, dog bequaam is om ...",Method=✓; Process=✓; Product=✗,COOKING_CREATION_Method='braden'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='braden'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='speenvarken',_vol002volm01_01.xml__ch19__speenvarken
2,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,roosemarijn,UNKNOWN,"…n den spit doen in eenen anderen pot, ende nemen den roosemarijn ende het speck wech, doetter by het vet datter sou...",Method=✗; Process=✓; Product=✓,COOKING_CREATION_Method='wegnemen'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='doetter by het vet datter soude moghen afghebraden wesen met wat malvesey oft spaenschen wi...,magi007kooc02_01.xml__ch10__roosemarijn
3,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,sap,RECIPE_PRACTICE,"…tste doet men 'er een ey klein geklopt met wat Limoensap onder, dan schud men het door een, en men laat het een qua...",Method=✓; Process=✗; Product=✓,COOKING_CREATION_Method=''; COOKING_CREATION_Process='opkoken'; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method=''; COOKING_CREATION_Process='stooven'; COOKING_CREATION_Food_Product='',_vol002volm01_01.xml__ch18__v_trekken__sap
4,partial_strong,yes,2,3,PRESERVING,PRESERVING,schol,RECIPE_PRACTICE,"neemt schol, maakt ze schoon, snyd 'er de vinnen af, en doet 'er al het ingewand uit, en hangt ze wat op om te drooge…",Technique=✓; Medium=✓; Patient=✗,PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='vis',PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='schol',preservare_2051__drying__schol
5,partial_strong,yes,2,3,PRESERVING,PRESERVING,tuinboon,RECIPE_PRACTICE,"…n welletje in regenwater opkooken: zet ze dan op een vergiettest te verzygen: dan legt men ze op tafels, op zolder,...",Technique=✗; Medium=✓; Patient=✓,PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='tuinboon',"PR_Technique='droogen op tafels, op zolder, digt aan het venster te droogen, op glazen te droogen'; PR_Medium=''; PR...",preservare_2415__drying__tuinboon
6,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,Artischokken,RECIPE_PRACTICE,"…op, die vry zyn van de vorst. Verscheide wyzen om de Artischokken klaar te maken. Artischokken met een zuure Peper-...",Method=✗; Process=✓; Product=✗,COOKING_CREATION_Method='klaarmaken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='snyd ze in vierendeels'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='artisc...,chom003huis01_01.xml__ch4__artischokken
7,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,Kruidnagelen,RECIPE_PRACTICE,"… kapt het fyn, en doet 'er zout, peper, Notemuscaat, Kruidnagelen, Champignons, morilles, booter, en zo het in den ...",Method=✗; Process=✗; Product=✓,COOKING_CREATION_Method='bakken'; COOKING_CREATION_Process='bakken'; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method=""doet 'er de graaten schoon uit, en het vel 'er ter degen af; kapt het fyn, en doet 'er zout...",_vol002volm01_01.xml__ch13__kruidnagelen
8,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,Kruidnagelen,RECIPE_PRACTICE,"…; kookt het in Vleeschnat; stooft het wel met Peper, Kruidnagelen, ende een glas Wyn. Gaar gekookt zynde, fruit Blo...",Method=✗; Process=✓; Product=✗,COOKING_CREATION_Method='stoven'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='ragout van haas',COOKING_CREATION_Method='gebraden'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='haas',cure_stepc__chom003huis01_01.xml__ch11__kruidnagelen__11771
9,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,garst,RECIPE_PRACTICE,"… van een Kalfs-schinkel, en men laat 'er wat gepelde garst of kruim van wittebrood daar onder kooken, en doet 'er w...",Method=✗; Process=✓; Product=✗,COOKING_CREATION_Method='maaken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='soep',COOKING_CREATION_Method='snyd'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',cure_stepc___vol002volm01_01.xml__ch8__garst__78084
10,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,mostacciolen,UNKNOWN,"…y pinten wijn, ende dry pinten azijn, ende dry oncen mostacciolen, siedt dit t'samen in eenen pot, ende alst wel gh...",Method=✗; Process=✗; Product=✓,COOKING_CREATION_Method='sieden'; COOKING_CREATION_Process='koken'; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method=""siedt dit t'samen in eenen pot""; COOKING_CREATION_Process='sieden, door den tempst'; COOKIN...",magi007kooc02_01.xml__ch8__mostacciolen
11,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,oesters,RECIPE_PRACTICE,"…e boter, maaktse heet, doet uw beslag in een pan, de oesters een voor een daar in, gebakkenzijnde, verzijgen, str…",Method=✗; Process=✓; Product=✗,COOKING_CREATION_Method='bakken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='doet uw beslag in een pan'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='oes...,preservare_4313__salting__oesters
12,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,soep,LITERARY,"…en. Bij dezelve laat zich geen leeuwrik braden, geen soep koken, geen pijp tabak opsteken. Hazen. Gulzige beesten, ...",Method=✗; Process=✗; Product=✓,COOKING_CREATION_Method='koken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='soep',COOKING_CREATION_Method=''; COOKING_CREATION_Process='soep koken'; COOKING_CREATION_Food_Product='soep',ingest_stepc___vad003183401_01.xml__ch359__soep__28369
13,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,spek,RECIPE_PRACTICE,"…e grond van de Casserol of stoof-pan, dunne sneedjes spek, daar men de schyf oplegt, en men doet 'er wat kalfsnat b...",Method=✗; Process=✓; Product=✗,COOKING_CREATION_Method='stooven'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='gaar in een groote ketel vol water'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Pro...,ingest_stepc___vol002volm01_01.xml__ch18__spek__66330
14,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,vlees,TRAVEL,"…rde aen, op een kleet of tapyt: braden en kooken hun vlees, doch niet recht gaer: scheppen in de jagt groot vermaek...",Method=✗; Process=✓; Product=✗,COOKING_CREATION_Method='braden'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='braden en kooken hun vlees'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='vl...,wits008noor02_01.xml__ch4__v_braden__vlees
15,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,wijn,MEDICAL,"… me’e voort &c. Sal fixum Tartari. ’t Vaste Sout van wijn-steen. Recipe. Tartari, die rauw doch fraay wit is, so ve...",Method=✗; Process=✗; Product=✓,COOKING_CREATION_Method=''; COOKING_CREATION_Process='smelten'; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='smelten'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',_lee024leeu02_01.xml__ch47__v_smelten__wijn
16,partial,,1,2,CURE,CURE,Azyn,RECIPE_PRACTICE,… doen ettelyke druppels van Maankoppezaad geweekt in Azyn: doch eerst moet men de plaats wryven met Salpeter. Enige...,Affliction=✓; Treatment=✗,CURE_Affliction='zweer'; CURE_Food_Treatment='op de wonde doen',CURE_Affliction='zweer'; CURE_Food_Treatment='ettelyke druppels van maankoppezaad geweekt in azyn',cure_stepc__chom003huis01_01.xml__ch19__azyn__71210
17,partial,,1,2,CURE,CURE,Olijven,UNKNOWN,"…cktse gloeyende, blust die in klare gemeyne olie van Olijven, stootse daer naer wel kleyn, ende distileert daer uyt...",Affliction=✓; Treatment=✗,CURE_Affliction='cataracten der oogen'; CURE_Food_Treatment='',CURE_Affliction='cataracten der oogen'; CURE_Food_Treatment='distileert daer uyt een water',bate002secr02_01.xml__ch97__olijven
18,partial,,1,5,INGESTION,INGESTION,thee,TRAVEL,"…r of aanhoudende aderlatingen genezen wilde, eeue apotheek nogtans of huismiddeltje aan de kwakzalvers overlatende....",Context=✗; Ingestor=✗; Manner=✗; Patient=✗; Purpose=✓,"INGESTION_Context='in a dutch colonial context, in paramaribo, suriname.'; INGESTION_Ingestor='the narrator and his ...",INGESTION_Context=''; INGESTION_Ingestor='de heer l. en de verteller (ik)'; INGESTION_Manner='dronken drinken'; INGE...,breu012dagv01_01.xml__ch3__v_genezen__thee
19,partial,,1,3,PRESERVING,PRESERVING,Aspersjes,RECIPE_PRACTICE,"…oogen, dog dan zyn ze zo goed niet in 't gebruik. 4. Aspersjes, hoe men die bewaren zal. Breekt het teedere van de ...",Technique=✗; Medium=✓; Patient=✗,PR_Technique='bespreng met zout'; PR_Medium='zout'; PR_Food_Patient='',PR_Technique='besprengen met zout'; PR_Medium='zout'; PR_Food_Patient='aspersjes',_vol002volm01_01.xml__ch15__aspersjes
20,partial,,1,3,PRESERVING,PRESERVING,Laurier,UNKNOWN,"…men de Gerste onbeschadigt bewaren sal. Neemt drooge Laurier-bladeren, van een Boom die vruchten draeght, smijt die...",Technique=✗; Medium=✓; Patient=✗,PR_Technique='onbeschadigd bewaren'; PR_Medium=''; PR_Food_Patient='',"PR_Technique='smijten onder de gerste'; PR_Medium=''; PR_Food_Patient='laurier-bladeren, laurier-hout, sempervivum, ...",bate002secr02_01.xml__ch63__laurier
21,partial,,1,3,PRESERVING,PRESERVING,Peterselie,MEDICAL,"… wortelen die stokachtig zyn als van oude Venkel, en Peterselie, dese kneust men met een hamertjen tot de schil wee...",Technique=✗; Medium=✓; Patient=✗,PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='',PR_Technique='droogen buiten de zon'; PR_Medium=''; PR_Food_Patient='peterselie',_pha001phar05_01.xml__ch16__peterselie
22,partial,,1,3,PRESERVING,PRESERVING,artisjokken stoelen,RECIPE_PRACTICE,"…t die een nacht in schoon water ververschen, dan zyn ze zo goed als of ze versch waren. men kan dezelve ook in de z...",Technique=✗; Medium=✓; Patient=✗,PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='artisjokken',PR_Technique='droogen in de zon of oven'; PR_Medium=''; PR_Food_Patient='artisjokken stoelen',preservare_2373__drying__artisjokken stoelen
23,partial,,1,3,PRESERVING,PRESERVING,bloemen,MEDICAL,"Gy sult nemen bloemen van wilde Druyven of van Hagen, als dien tijdt zijn sal, ende de selve doet drooge in de schay...",Technique=✗; Medium=✓; Patient=✗,PR_Technique='drying'; PR_Medium=''; PR_Food_Patient='bloemen (flowers)',PR_Technique='drooge in de schaye en bewaertse in een sacksken'; PR_Medium=''; PR_Food_Patient='bloemen van wilde dr...,inception_nl__selected_texts_txt__dekker__s19__5453__bloemen
24,partial,,1,3,PRESERVING,PRESERVING,boerenbonen,RECIPE_PRACTICE,"…rood daar uitgekomen is; laatze dus staan, tot ze droog genoeg zyn. sommigen verkiezen ze in plaats van in een oven...",Technique=✗; Medium=✓; Patient=✗,PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='peulvruchten',PR_Technique='droogen in de sterke lucht'; PR_Medium=''; PR_Food_Patient='boerenbonen',preservare_2936__drying__boerenbonen
25,partial,,1,3,PRESERVING,PRESERVING,champignons,RECIPE_PRACTICE,…dat ze anders zouden verrotten; ook moet men die op een koele plaats in de kelder zetten. men kan ze ook laaten in ...,Technique=✗; Medium=✓; Patient=✗,PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='paddestoelen',PR_Technique='droogen in de zon of op den ooven'; PR_Medium=''; PR_Food_Patient='champignons',preservare_2417__drying__champignons
26,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,Neuten-olie,MEDICAL,"…en’er zout in smelten, daar men Honig en Olyven-, of Neuten-olie by doet. Als alles is met den anderen gemengd, zet...",Method=✗; Process=✗; Product=✗,"COOKING_CREATION_Method='smelten zout en oliën'; COOKING_CREATION_Process='lywaat gebruiken, smeltering van ingredië...","COOKING_CREATION_Method='smelten, by doen'; COOKING_CREATION_Process='lywaat lopen, zout smelten, honig en olyven-, ...",inception_nl__selected_texts_txt__dekker__s39__11396__neuten_olie
27,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,aardappelen,LITERARY,"…n de oogen en antwoordde plechtig: ‘Reginald, ik kan aardappelen koken op vijftien verschillende manieren!’ Dan leg...",Method=✗; Process=✗; Product=✗,COOKING_CREATION_Method=''; COOKING_CREATION_Process='koken'; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='aardappelen koken op vijftien verschillende manieren'; COOKING_CREATION_Process=''; COOKING...,_hui002189901_01.xml__ch117__v_koken__aardappelen
28,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,artischokken,RECIPE_PRACTICE,"…celie, met wat zout, peper, Notemuscaat, stoelen van artischokken en pistaches, doet het in een korst en zet het te...",Method=✗; Process=✗; Product=✗,COOKING_CREATION_Method='bakken'; COOKING_CREATION_Process='bakken'; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method='hakt ze fyn met wat booter, champignons, petercelie, met wat zout, peper, notemuscaat, stoe...",_vol002volm01_01.xml__ch13__artischokken
29,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,broodzuiker,RECIPE_PRACTICE,"… 'er wat Rose-water of Oranje-water op, en raspt 'er broodzuiker over heen, sluit het dan met de boven-korst en zet...",Method=✗; Process=✗; Product=✗,COOKING_CREATION_Method='raspen'; COOKING_CREATION_Process='bakken'; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method='raspt'; COOKING_CREATION_Process='styven op het vuur, koud laten worden, rose-water of oran...",_vol002volm01_01.xml__ch13__broodzuiker
30,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,koe,UNKNOWN,…l.67. Manieren van Stoven. Lendenen van eenen Os oft Koe.67. Kalfs-borst te stoven.69. Capuynen ende Hinnen.69.,Method=✗; Process=✗; Product=✗,COOKING_CREATION_Method='stoven'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method=''; COOKING_CREATION_Process='stoving'; COOKING_CREATION_Food_Product='kalfs-borst',magi007kooc02_01.xml__ch15__v_stoven__koe
31,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,oesters,UNKNOWN,…e koken.110. Hoemen Vorschen koken sal.111. Hoemen d'Oesters koken sal.111. Maniere om 'tFruyt te dienen.112.,Method=✗; Process=✗; Product=✗,COOKING_CREATION_Method=''; COOKING_CREATION_Process='koken'; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method=""hoemen d'oesters koken sal.""; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='o...",magi007kooc02_01.xml__ch15__v_koken__oesters
32,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,olie,MEDICAL,"Uitgeperste Olien. Oleum Amygdalarum Dulcium. NEemt drooge, soete Amandelen, die niet rans en zyn, soo veel gy wilt....",Method=✗; Process=✗; Product=✗,COOKING_CREATION_Method=''; COOKING_CREATION_Process='persen'; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method='persting'; COOKING_CREATION_Process='verwarmen, persten'; COOKING_CREATION_Food_Product='olie'",_pha001phar05_01.xml__ch28__v_maken__olie
33,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,vlees,UNKNOWN,"…r men moet wel toe sien dat het yser nievers aen het vlees en raeckt, want men doet dit maer om hem van binnen droo...",Method=✗; Process=✗; Product=✗,COOKING_CREATION_Method='droog maken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method='broeyen, plucken, drooch, vullen met vulsels, broeyen, steecken in warm water, cout worden,...",magi007kooc02_01.xml__ch8__v_broeyen__vlees
34,frame_ok_zero,,0,2,CURE,CURE,Amandelen,RECIPE_PRACTICE,"…ofd. Men zal ook raauwe Vrugten toelaten, als Vygen, Amandelen, Persikken, Appelen, Peren. De Drank moet klein Bier...",Affliction=✗; Treatment=✗,CURE_Affliction='uitterende koorts'; CURE_Food_Treatment='',CURE_Affliction='derdendaagse koorts'; CURE_Food_Treatment='eten van amandelen',cure_stepc__chom003huis01_01.xml__ch13__amandelen__48177
35,frame_ok_zero,,0,2,CURE,CURE,Azijn,UNKNOWN,"… soo sal men daer by gieten sap van Porceleyne, ende Azijn, elcks even veel te samen gemenght. Ofte bestrijckt den ...",Affliction=✗; Treatment=✗,CURE_Affliction='van de mieren gequelt'; CURE_Food_Treatment='bij gieten',CURE_Affliction=''; CURE_Food_Treatment='',cure_stepc__bate002secr02_01.xml__ch53__azijn__65292
36,frame_ok_zero,,0,2,CURE,CURE,Kaneel,RECIPE_PRACTICE,"…r te maken, kan men vyf, of zes druppen Essentie van Kaneel in de Brandewyn mengen, welke men gebruikt, om ’t Zout ...",Affliction=✗; Treatment=✗,"CURE_Affliction='de tering, benaaude borst, en andere longeziekten'; CURE_Food_Treatment='genezen'","CURE_Affliction='verstoppingen van den onderbuik, de tering, benaaude borst, en andere longeziekten'; CURE_Food_Trea...",chom003huis01_01.xml__ch15__kaneel
37,frame_ok_zero,,0,2,CURE,CURE,Kaneel,RECIPE_PRACTICE,"…rstoppingen der Stonden te genezen, moet men Suiker, Kaneel, en Sap van Hyssoop by de zelfde menigte doen. Men geef...",Affliction=✗; Treatment=✗,CURE_Affliction='verstoppingen der stonden'; CURE_Food_Treatment='genezen',"CURE_Affliction='apoplexie, maagkwalen en stuipen'; CURE_Food_Treatment='toevoegen'",chom003huis01_01.xml__ch21__kaneel
38,frame_ok_zero,,0,2,CURE,CURE,Salie,RECIPE_PRACTICE,"…de tanden vast te zetten. XLIV. Men moet een handvol Salie nemen, ze in een half pond goede rode Wyn laten koken, d...",Affliction=✗; Treatment=✗,CURE_Affliction='losse tand'; CURE_Food_Treatment='spoelen',CURE_Affliction='tanden vast te zetten'; CURE_Food_Treatment='warm spoelen',cure_stepc__chom003huis01_01.xml__ch22__salie__68404
39,frame_ok_zero,,0,2,CURE,CURE,Suiker,RECIPE_PRACTICE,"…Om de verstoppingen der Stonden te genezen, moet men Suiker, Kaneel, en Sap van Hyssoop by de zelfde menigte doen. ...",Affliction=✗; Treatment=✗,CURE_Affliction='verstoppingen der stonden'; CURE_Food_Treatment='genezen',"CURE_Affliction='ssentie is uitnemend voor de toevallen der apoplexie, voor maagkwalen en stuipen'; CURE_Food_Treatm...",chom003huis01_01.xml__ch21__suiker
40,frame_ok_zero,,0,2,CURE,CURE,Varkens,RECIPE_PRACTICE,"…met Azyn, en vryft het dan weder over met ongezouten Varkens Reusel en teer onder een gesmolten. Deze Zal hare deug...",Affliction=✗; Treatment=✗,CURE_Affliction=''; CURE_Food_Treatment='genezen',CURE_Affliction='ongezouten varkens reusel en teer onder een gesmolten'; CURE_Food_Treatment='wryft daar mede het ve...,chom003huis01_01.xml__ch14__varkens
41,frame_ok_zero,,0,2,CURE,CURE,Verjuis,RECIPE_PRACTICE,"… een deel Wyn-azyn met vyf, of zes deelen water. Het Verjuis zoude nog beter zyn, dan de Wyn-azyn Algemeene Geneesm...",Affliction=✗; Treatment=✗,CURE_Affliction=''; CURE_Food_Treatment='genezen',"CURE_Affliction='ziekten der armen'; CURE_Food_Treatment='geven, die gema'",chom003huis01_01.xml__ch20__verjuis
42,frame_ok_zero,,0,2,CURE,CURE,Vlier,UNKNOWN,"…s een Paert niet stallen en kan. Soo neemt Meyen van Vlier-boom, ende slaet het Paerdt daer mede over sijn gantsche...",Affliction=✗; Treatment=✗,CURE_Affliction='niet stallen'; CURE_Food_Treatment='slaet het daarmede',"CURE_Affliction='vliegen ontrent komen'; CURE_Food_Treatment='nat het hayr van de paerden, ende van alle andere gedi...",cure_stepc__bate002secr02_01.xml__ch17__vlier__13175

,tier,fewshot_candidate,hits,n_fields,gold_frame,pred_frame,target_word,text_regime,context_snippet,field_hits,gold_fields,pred_fields,record_id
0,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,Kruidnagelen,RECIPE_PRACTICE,"…oral eer ze op den Rooster gelegt worden, met...",Method=✗; Process=✓; Product=✓,COOKING_CREATION_Method='besteken'; COOKING_CR...,"COOKING_CREATION_Method='sneeden, met eenige k...",chom003huis01_01.xml__ch6__kruidnagelen
1,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,Speenvarken,RECIPE_PRACTICE,…n heeft het geen zwarigheid: Ook moet men noo...,Method=✓; Process=✓; Product=✗,COOKING_CREATION_Method='braden'; COOKING_CREA...,COOKING_CREATION_Method='braden'; COOKING_CREA...,_vol002volm01_01.xml__ch19__speenvarken
2,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,roosemarijn,UNKNOWN,"…n den spit doen in eenen anderen pot, ende ne...",Method=✗; Process=✓; Product=✓,COOKING_CREATION_Method='wegnemen'; COOKING_CR...,COOKING_CREATION_Method='doetter by het vet da...,magi007kooc02_01.xml__ch10__roosemarijn
3,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,sap,RECIPE_PRACTICE,…tste doet men 'er een ey klein geklopt met wa...,Method=✓; Process=✗; Product=✓,COOKING_CREATION_Method=''; COOKING_CREATION_P...,COOKING_CREATION_Method=''; COOKING_CREATION_P...,_vol002volm01_01.xml__ch18__v_trekken__sap
4,partial_strong,yes,2,3,PRESERVING,PRESERVING,schol,RECIPE_PRACTICE,"neemt schol, maakt ze schoon, snyd 'er de vinn...",Technique=✓; Medium=✓; Patient=✗,PR_Technique='droogen'; PR_Medium=''; PR_Food_...,PR_Technique='droogen'; PR_Medium=''; PR_Food_...,preservare_2051__drying__schol
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,miss,,0,3,PRESERVING,COOKING_CREATION,snoek,RECIPE_PRACTICE,"snijdse in stukken, strooyt'er zouten ziedend ...",Technique=✗; Medium=✗; Patient=✗,PR_Technique='kooken'; PR_Medium='azijn. water...,"COOKING_CREATION_Method=""snijdse in stukken, s...",preservare_4338__salting__snoek
89,miss,,0,3,PRESERVING,COOKING_CREATION,snoek,RECIPE_PRACTICE,"schrapt, ontweyd, wastse, en brengt de kop en ...",Technique=✗; Medium=✗; Patient=✗,PR_Technique='kooken'; PR_Medium='water'; PR_F...,"COOKING_CREATION_Method='kooktse in water, zou...",preservare_4336__salting__snoek
90,miss,,0,3,PRESERVING,COOKING_CREATION,soep,RECIPE_PRACTICE,"…af, edat het dik in de pot blyve; doe de soup...",Technique=✗; Medium=✗; Patient=✗,PR_Technique='gisten'; PR_Medium='licht'; PR_F...,COOKING_CREATION_Method='dik in de pot blyve';...,preservare_3181__fermentation__soep
91,miss,,0,3,PRESERVING,COOKING_CREATION,vet,RECIPE_PRACTICE,"…n, hoe men die voor de winter zal inzouten. D...",Technique=✗; Medium=✗; Patient=✗,PR_Technique='soucing'; PR_Medium='salt'; PR_F...,COOKING_CREATION_Method='kookt ze een welletje...,_vol002volm01_01.xml__ch17__vet
92,miss,,0,3,PRESERVING,COOKING_CREATION,worst,RECIPE_PRACTICE,"…t het in varkens-darmen, zoo lang als u doenl...",Technique=✗; Medium=✗; Patient=✗,PR_Technique='droogen'; PR_Medium=''; PR_Food_...,COOKING_CREATION_Method='braaden'; COOKING_CRE...,preservare_3604__drying__worst

## Filter with pandas (no widgets)

Change the boolean mask, re-run.

In [4]:
# Examples — uncomment one:
# slice_ = review[review['tier'].isin(['joint', 'partial_strong'])]
# slice_ = review[review['gold_frame'] == 'COOKING_CREATION']
# slice_ = review[review['fewshot_candidate'].astype(str).str.len() > 0]
slice_ = review.copy()

print(review_summary(slice_))
show_review(slice_, CONFIG)

{'rows': 93, 'tiers': {'miss': 40, 'frame_ok_zero': 27, 'partial': 20, 'partial_strong': 6}, 'fewshot_flagged': 16, 'by_frame': {'COOKING_CREATION': 31, 'PRESERVING': 27, 'CURE': 24, 'INGESTION': 11}}

,tier,fewshot_candidate,hits,n_fields,gold_frame,pred_frame,target_word,text_regime,context_snippet,field_hits,gold_fields,pred_fields,record_id
0,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,Kruidnagelen,RECIPE_PRACTICE,"…oral eer ze op den Rooster gelegt worden, met eenige Kruidnagelen, en Lauwrierbladen besteken; en ze vervolgens met...",Method=✗; Process=✓; Product=✓,COOKING_CREATION_Method='besteken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method='sneeden, met eenige kruidnagelen, en lauwrierbladen besteken'; COOKING_CREATION_Process='';...",chom003huis01_01.xml__ch6__kruidnagelen
1,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,Speenvarken,RECIPE_PRACTICE,"…n heeft het geen zwarigheid: Ook moet men nooit geen Speenvarken braden, dan het geen nog zuigt, dog bequaam is om ...",Method=✓; Process=✓; Product=✗,COOKING_CREATION_Method='braden'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='braden'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='speenvarken',_vol002volm01_01.xml__ch19__speenvarken
2,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,roosemarijn,UNKNOWN,"…n den spit doen in eenen anderen pot, ende nemen den roosemarijn ende het speck wech, doetter by het vet datter sou...",Method=✗; Process=✓; Product=✓,COOKING_CREATION_Method='wegnemen'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='doetter by het vet datter soude moghen afghebraden wesen met wat malvesey oft spaenschen wi...,magi007kooc02_01.xml__ch10__roosemarijn
3,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,sap,RECIPE_PRACTICE,"…tste doet men 'er een ey klein geklopt met wat Limoensap onder, dan schud men het door een, en men laat het een qua...",Method=✓; Process=✗; Product=✓,COOKING_CREATION_Method=''; COOKING_CREATION_Process='opkoken'; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method=''; COOKING_CREATION_Process='stooven'; COOKING_CREATION_Food_Product='',_vol002volm01_01.xml__ch18__v_trekken__sap
4,partial_strong,yes,2,3,PRESERVING,PRESERVING,schol,RECIPE_PRACTICE,"neemt schol, maakt ze schoon, snyd 'er de vinnen af, en doet 'er al het ingewand uit, en hangt ze wat op om te drooge…",Technique=✓; Medium=✓; Patient=✗,PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='vis',PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='schol',preservare_2051__drying__schol
5,partial_strong,yes,2,3,PRESERVING,PRESERVING,tuinboon,RECIPE_PRACTICE,"…n welletje in regenwater opkooken: zet ze dan op een vergiettest te verzygen: dan legt men ze op tafels, op zolder,...",Technique=✗; Medium=✓; Patient=✓,PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='tuinboon',"PR_Technique='droogen op tafels, op zolder, digt aan het venster te droogen, op glazen te droogen'; PR_Medium=''; PR...",preservare_2415__drying__tuinboon
6,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,Artischokken,RECIPE_PRACTICE,"…op, die vry zyn van de vorst. Verscheide wyzen om de Artischokken klaar te maken. Artischokken met een zuure Peper-...",Method=✗; Process=✓; Product=✗,COOKING_CREATION_Method='klaarmaken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='snyd ze in vierendeels'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='artisc...,chom003huis01_01.xml__ch4__artischokken
7,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,Kruidnagelen,RECIPE_PRACTICE,"… kapt het fyn, en doet 'er zout, peper, Notemuscaat, Kruidnagelen, Champignons, morilles, booter, en zo het in den ...",Method=✗; Process=✗; Product=✓,COOKING_CREATION_Method='bakken'; COOKING_CREATION_Process='bakken'; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method=""doet 'er de graaten schoon uit, en het vel 'er ter degen af; kapt het fyn, en doet 'er zout...",_vol002volm01_01.xml__ch13__kruidnagelen
8,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,Kruidnagelen,RECIPE_PRACTICE,"…; kookt het in Vleeschnat; stooft het wel met Peper, Kruidnagelen, ende een glas Wyn. Gaar gekookt zynde, fruit Blo...",Method=✗; Process=✓; Product=✗,COOKING_CREATION_Method='stoven'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='ragout van haas',COOKING_CREATION_Method='gebraden'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='haas',cure_stepc__chom003huis01_01.xml__ch11__kruidnagelen__11771
9,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,garst,RECIPE_PRACTICE,"… van een Kalfs-schinkel, en men laat 'er wat gepelde garst of kruim van wittebrood daar onder kooken, en doet 'er w...",Method=✗; Process=✓; Product=✗,COOKING_CREATION_Method='maaken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='soep',COOKING_CREATION_Method='snyd'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',cure_stepc___vol002volm01_01.xml__ch8__garst__78084
10,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,mostacciolen,UNKNOWN,"…y pinten wijn, ende dry pinten azijn, ende dry oncen mostacciolen, siedt dit t'samen in eenen pot, ende alst wel gh...",Method=✗; Process=✗; Product=✓,COOKING_CREATION_Method='sieden'; COOKING_CREATION_Process='koken'; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method=""siedt dit t'samen in eenen pot""; COOKING_CREATION_Process='sieden, door den tempst'; COOKIN...",magi007kooc02_01.xml__ch8__mostacciolen
11,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,oesters,RECIPE_PRACTICE,"…e boter, maaktse heet, doet uw beslag in een pan, de oesters een voor een daar in, gebakkenzijnde, verzijgen, str…",Method=✗; Process=✓; Product=✗,COOKING_CREATION_Method='bakken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='doet uw beslag in een pan'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='oes...,preservare_4313__salting__oesters
12,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,soep,LITERARY,"…en. Bij dezelve laat zich geen leeuwrik braden, geen soep koken, geen pijp tabak opsteken. Hazen. Gulzige beesten, ...",Method=✗; Process=✗; Product=✓,COOKING_CREATION_Method='koken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='soep',COOKING_CREATION_Method=''; COOKING_CREATION_Process='soep koken'; COOKING_CREATION_Food_Product='soep',ingest_stepc___vad003183401_01.xml__ch359__soep__28369
13,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,spek,RECIPE_PRACTICE,"…e grond van de Casserol of stoof-pan, dunne sneedjes spek, daar men de schyf oplegt, en men doet 'er wat kalfsnat b...",Method=✗; Process=✓; Product=✗,COOKING_CREATION_Method='stooven'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='gaar in een groote ketel vol water'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Pro...,ingest_stepc___vol002volm01_01.xml__ch18__spek__66330
14,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,vlees,TRAVEL,"…rde aen, op een kleet of tapyt: braden en kooken hun vlees, doch niet recht gaer: scheppen in de jagt groot vermaek...",Method=✗; Process=✓; Product=✗,COOKING_CREATION_Method='braden'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='braden en kooken hun vlees'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='vl...,wits008noor02_01.xml__ch4__v_braden__vlees
15,partial,maybe,1,3,COOKING_CREATION,COOKING_CREATION,wijn,MEDICAL,"… me’e voort &c. Sal fixum Tartari. ’t Vaste Sout van wijn-steen. Recipe. Tartari, die rauw doch fraay wit is, so ve...",Method=✗; Process=✗; Product=✓,COOKING_CREATION_Method=''; COOKING_CREATION_Process='smelten'; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='smelten'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',_lee024leeu02_01.xml__ch47__v_smelten__wijn
16,partial,,1,2,CURE,CURE,Azyn,RECIPE_PRACTICE,… doen ettelyke druppels van Maankoppezaad geweekt in Azyn: doch eerst moet men de plaats wryven met Salpeter. Enige...,Affliction=✓; Treatment=✗,CURE_Affliction='zweer'; CURE_Food_Treatment='op de wonde doen',CURE_Affliction='zweer'; CURE_Food_Treatment='ettelyke druppels van maankoppezaad geweekt in azyn',cure_stepc__chom003huis01_01.xml__ch19__azyn__71210
17,partial,,1,2,CURE,CURE,Olijven,UNKNOWN,"…cktse gloeyende, blust die in klare gemeyne olie van Olijven, stootse daer naer wel kleyn, ende distileert daer uyt...",Affliction=✓; Treatment=✗,CURE_Affliction='cataracten der oogen'; CURE_Food_Treatment='',CURE_Affliction='cataracten der oogen'; CURE_Food_Treatment='distileert daer uyt een water',bate002secr02_01.xml__ch97__olijven
18,partial,,1,5,INGESTION,INGESTION,thee,TRAVEL,"…r of aanhoudende aderlatingen genezen wilde, eeue apotheek nogtans of huismiddeltje aan de kwakzalvers overlatende....",Context=✗; Ingestor=✗; Manner=✗; Patient=✗; Purpose=✓,"INGESTION_Context='in a dutch colonial context, in paramaribo, suriname.'; INGESTION_Ingestor='the narrator and his ...",INGESTION_Context=''; INGESTION_Ingestor='de heer l. en de verteller (ik)'; INGESTION_Manner='dronken drinken'; INGE...,breu012dagv01_01.xml__ch3__v_genezen__thee
19,partial,,1,3,PRESERVING,PRESERVING,Aspersjes,RECIPE_PRACTICE,"…oogen, dog dan zyn ze zo goed niet in 't gebruik. 4. Aspersjes, hoe men die bewaren zal. Breekt het teedere van de ...",Technique=✗; Medium=✓; Patient=✗,PR_Technique='bespreng met zout'; PR_Medium='zout'; PR_Food_Patient='',PR_Technique='besprengen met zout'; PR_Medium='zout'; PR_Food_Patient='aspersjes',_vol002volm01_01.xml__ch15__aspersjes
20,partial,,1,3,PRESERVING,PRESERVING,Laurier,UNKNOWN,"…men de Gerste onbeschadigt bewaren sal. Neemt drooge Laurier-bladeren, van een Boom die vruchten draeght, smijt die...",Technique=✗; Medium=✓; Patient=✗,PR_Technique='onbeschadigd bewaren'; PR_Medium=''; PR_Food_Patient='',"PR_Technique='smijten onder de gerste'; PR_Medium=''; PR_Food_Patient='laurier-bladeren, laurier-hout, sempervivum, ...",bate002secr02_01.xml__ch63__laurier
21,partial,,1,3,PRESERVING,PRESERVING,Peterselie,MEDICAL,"… wortelen die stokachtig zyn als van oude Venkel, en Peterselie, dese kneust men met een hamertjen tot de schil wee...",Technique=✗; Medium=✓; Patient=✗,PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='',PR_Technique='droogen buiten de zon'; PR_Medium=''; PR_Food_Patient='peterselie',_pha001phar05_01.xml__ch16__peterselie
22,partial,,1,3,PRESERVING,PRESERVING,artisjokken stoelen,RECIPE_PRACTICE,"…t die een nacht in schoon water ververschen, dan zyn ze zo goed als of ze versch waren. men kan dezelve ook in de z...",Technique=✗; Medium=✓; Patient=✗,PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='artisjokken',PR_Technique='droogen in de zon of oven'; PR_Medium=''; PR_Food_Patient='artisjokken stoelen',preservare_2373__drying__artisjokken stoelen
23,partial,,1,3,PRESERVING,PRESERVING,bloemen,MEDICAL,"Gy sult nemen bloemen van wilde Druyven of van Hagen, als dien tijdt zijn sal, ende de selve doet drooge in de schay...",Technique=✗; Medium=✓; Patient=✗,PR_Technique='drying'; PR_Medium=''; PR_Food_Patient='bloemen (flowers)',PR_Technique='drooge in de schaye en bewaertse in een sacksken'; PR_Medium=''; PR_Food_Patient='bloemen van wilde dr...,inception_nl__selected_texts_txt__dekker__s19__5453__bloemen
24,partial,,1,3,PRESERVING,PRESERVING,boerenbonen,RECIPE_PRACTICE,"…rood daar uitgekomen is; laatze dus staan, tot ze droog genoeg zyn. sommigen verkiezen ze in plaats van in een oven...",Technique=✗; Medium=✓; Patient=✗,PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='peulvruchten',PR_Technique='droogen in de sterke lucht'; PR_Medium=''; PR_Food_Patient='boerenbonen',preservare_2936__drying__boerenbonen
25,partial,,1,3,PRESERVING,PRESERVING,champignons,RECIPE_PRACTICE,…dat ze anders zouden verrotten; ook moet men die op een koele plaats in de kelder zetten. men kan ze ook laaten in ...,Technique=✗; Medium=✓; Patient=✗,PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='paddestoelen',PR_Technique='droogen in de zon of op den ooven'; PR_Medium=''; PR_Food_Patient='champignons',preservare_2417__drying__champignons
26,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,Neuten-olie,MEDICAL,"…en’er zout in smelten, daar men Honig en Olyven-, of Neuten-olie by doet. Als alles is met den anderen gemengd, zet...",Method=✗; Process=✗; Product=✗,"COOKING_CREATION_Method='smelten zout en oliën'; COOKING_CREATION_Process='lywaat gebruiken, smeltering van ingredië...","COOKING_CREATION_Method='smelten, by doen'; COOKING_CREATION_Process='lywaat lopen, zout smelten, honig en olyven-, ...",inception_nl__selected_texts_txt__dekker__s39__11396__neuten_olie
27,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,aardappelen,LITERARY,"…n de oogen en antwoordde plechtig: ‘Reginald, ik kan aardappelen koken op vijftien verschillende manieren!’ Dan leg...",Method=✗; Process=✗; Product=✗,COOKING_CREATION_Method=''; COOKING_CREATION_Process='koken'; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method='aardappelen koken op vijftien verschillende manieren'; COOKING_CREATION_Process=''; COOKING...,_hui002189901_01.xml__ch117__v_koken__aardappelen
28,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,artischokken,RECIPE_PRACTICE,"…celie, met wat zout, peper, Notemuscaat, stoelen van artischokken en pistaches, doet het in een korst en zet het te...",Method=✗; Process=✗; Product=✗,COOKING_CREATION_Method='bakken'; COOKING_CREATION_Process='bakken'; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method='hakt ze fyn met wat booter, champignons, petercelie, met wat zout, peper, notemuscaat, stoe...",_vol002volm01_01.xml__ch13__artischokken
29,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,broodzuiker,RECIPE_PRACTICE,"… 'er wat Rose-water of Oranje-water op, en raspt 'er broodzuiker over heen, sluit het dan met de boven-korst en zet...",Method=✗; Process=✗; Product=✗,COOKING_CREATION_Method='raspen'; COOKING_CREATION_Process='bakken'; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method='raspt'; COOKING_CREATION_Process='styven op het vuur, koud laten worden, rose-water of oran...",_vol002volm01_01.xml__ch13__broodzuiker
30,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,koe,UNKNOWN,…l.67. Manieren van Stoven. Lendenen van eenen Os oft Koe.67. Kalfs-borst te stoven.69. Capuynen ende Hinnen.69.,Method=✗; Process=✗; Product=✗,COOKING_CREATION_Method='stoven'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',COOKING_CREATION_Method=''; COOKING_CREATION_Process='stoving'; COOKING_CREATION_Food_Product='kalfs-borst',magi007kooc02_01.xml__ch15__v_stoven__koe
31,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,oesters,UNKNOWN,…e koken.110. Hoemen Vorschen koken sal.111. Hoemen d'Oesters koken sal.111. Maniere om 'tFruyt te dienen.112.,Method=✗; Process=✗; Product=✗,COOKING_CREATION_Method=''; COOKING_CREATION_Process='koken'; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method=""hoemen d'oesters koken sal.""; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='o...",magi007kooc02_01.xml__ch15__v_koken__oesters
32,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,olie,MEDICAL,"Uitgeperste Olien. Oleum Amygdalarum Dulcium. NEemt drooge, soete Amandelen, die niet rans en zyn, soo veel gy wilt....",Method=✗; Process=✗; Product=✗,COOKING_CREATION_Method=''; COOKING_CREATION_Process='persen'; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method='persting'; COOKING_CREATION_Process='verwarmen, persten'; COOKING_CREATION_Food_Product='olie'",_pha001phar05_01.xml__ch28__v_maken__olie
33,frame_ok_zero,,0,3,COOKING_CREATION,COOKING_CREATION,vlees,UNKNOWN,"…r men moet wel toe sien dat het yser nievers aen het vlees en raeckt, want men doet dit maer om hem van binnen droo...",Method=✗; Process=✗; Product=✗,COOKING_CREATION_Method='droog maken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='',"COOKING_CREATION_Method='broeyen, plucken, drooch, vullen met vulsels, broeyen, steecken in warm water, cout worden,...",magi007kooc02_01.xml__ch8__v_broeyen__vlees
34,frame_ok_zero,,0,2,CURE,CURE,Amandelen,RECIPE_PRACTICE,"…ofd. Men zal ook raauwe Vrugten toelaten, als Vygen, Amandelen, Persikken, Appelen, Peren. De Drank moet klein Bier...",Affliction=✗; Treatment=✗,CURE_Affliction='uitterende koorts'; CURE_Food_Treatment='',CURE_Affliction='derdendaagse koorts'; CURE_Food_Treatment='eten van amandelen',cure_stepc__chom003huis01_01.xml__ch13__amandelen__48177
35,frame_ok_zero,,0,2,CURE,CURE,Azijn,UNKNOWN,"… soo sal men daer by gieten sap van Porceleyne, ende Azijn, elcks even veel te samen gemenght. Ofte bestrijckt den ...",Affliction=✗; Treatment=✗,CURE_Affliction='van de mieren gequelt'; CURE_Food_Treatment='bij gieten',CURE_Affliction=''; CURE_Food_Treatment='',cure_stepc__bate002secr02_01.xml__ch53__azijn__65292
36,frame_ok_zero,,0,2,CURE,CURE,Kaneel,RECIPE_PRACTICE,"…r te maken, kan men vyf, of zes druppen Essentie van Kaneel in de Brandewyn mengen, welke men gebruikt, om ’t Zout ...",Affliction=✗; Treatment=✗,"CURE_Affliction='de tering, benaaude borst, en andere longeziekten'; CURE_Food_Treatment='genezen'","CURE_Affliction='verstoppingen van den onderbuik, de tering, benaaude borst, en andere longeziekten'; CURE_Food_Trea...",chom003huis01_01.xml__ch15__kaneel
37,frame_ok_zero,,0,2,CURE,CURE,Kaneel,RECIPE_PRACTICE,"…rstoppingen der Stonden te genezen, moet men Suiker, Kaneel, en Sap van Hyssoop by de zelfde menigte doen. Men geef...",Affliction=✗; Treatment=✗,CURE_Affliction='verstoppingen der stonden'; CURE_Food_Treatment='genezen',"CURE_Affliction='apoplexie, maagkwalen en stuipen'; CURE_Food_Treatment='toevoegen'",chom003huis01_01.xml__ch21__kaneel
38,frame_ok_zero,,0,2,CURE,CURE,Salie,RECIPE_PRACTICE,"…de tanden vast te zetten. XLIV. Men moet een handvol Salie nemen, ze in een half pond goede rode Wyn laten koken, d...",Affliction=✗; Treatment=✗,CURE_Affliction='losse tand'; CURE_Food_Treatment='spoelen',CURE_Affliction='tanden vast te zetten'; CURE_Food_Treatment='warm spoelen',cure_stepc__chom003huis01_01.xml__ch22__salie__68404
39,frame_ok_zero,,0,2,CURE,CURE,Suiker,RECIPE_PRACTICE,"…Om de verstoppingen der Stonden te genezen, moet men Suiker, Kaneel, en Sap van Hyssoop by de zelfde menigte doen. ...",Affliction=✗; Treatment=✗,CURE_Affliction='verstoppingen der stonden'; CURE_Food_Treatment='genezen',"CURE_Affliction='ssentie is uitnemend voor de toevallen der apoplexie, voor maagkwalen en stuipen'; CURE_Food_Treatm...",chom003huis01_01.xml__ch21__suiker
40,frame_ok_zero,,0,2,CURE,CURE,Varkens,RECIPE_PRACTICE,"…met Azyn, en vryft het dan weder over met ongezouten Varkens Reusel en teer onder een gesmolten. Deze Zal hare deug...",Affliction=✗; Treatment=✗,CURE_Affliction=''; CURE_Food_Treatment='genezen',CURE_Affliction='ongezouten varkens reusel en teer onder een gesmolten'; CURE_Food_Treatment='wryft daar mede het ve...,chom003huis01_01.xml__ch14__varkens
41,frame_ok_zero,,0,2,CURE,CURE,Verjuis,RECIPE_PRACTICE,"… een deel Wyn-azyn met vyf, of zes deelen water. Het Verjuis zoude nog beter zyn, dan de Wyn-azyn Algemeene Geneesm...",Affliction=✗; Treatment=✗,CURE_Affliction=''; CURE_Food_Treatment='genezen',"CURE_Affliction='ziekten der armen'; CURE_Food_Treatment='geven, die gema'",chom003huis01_01.xml__ch20__verjuis
42,frame_ok_zero,,0,2,CURE,CURE,Vlier,UNKNOWN,"…s een Paert niet stallen en kan. Soo neemt Meyen van Vlier-boom, ende slaet het Paerdt daer mede over sijn gantsche...",Affliction=✗; Treatment=✗,CURE_Affliction='niet stallen'; CURE_Food_Treatment='slaet het daarmede',"CURE_Affliction='vliegen ontrent komen'; CURE_Food_Treatment='nat het hayr van de paerden, ende van alle andere gedi...",cure_stepc__bate002secr02_01.xml__ch17__vlier__13175

,tier,fewshot_candidate,hits,n_fields,gold_frame,pred_frame,target_word,text_regime,context_snippet,field_hits,gold_fields,pred_fields,record_id
0,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,Kruidnagelen,RECIPE_PRACTICE,"…oral eer ze op den Rooster gelegt worden, met...",Method=✗; Process=✓; Product=✓,COOKING_CREATION_Method='besteken'; COOKING_CR...,"COOKING_CREATION_Method='sneeden, met eenige k...",chom003huis01_01.xml__ch6__kruidnagelen
1,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,Speenvarken,RECIPE_PRACTICE,…n heeft het geen zwarigheid: Ook moet men noo...,Method=✓; Process=✓; Product=✗,COOKING_CREATION_Method='braden'; COOKING_CREA...,COOKING_CREATION_Method='braden'; COOKING_CREA...,_vol002volm01_01.xml__ch19__speenvarken
2,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,roosemarijn,UNKNOWN,"…n den spit doen in eenen anderen pot, ende ne...",Method=✗; Process=✓; Product=✓,COOKING_CREATION_Method='wegnemen'; COOKING_CR...,COOKING_CREATION_Method='doetter by het vet da...,magi007kooc02_01.xml__ch10__roosemarijn
3,partial_strong,yes,2,3,COOKING_CREATION,COOKING_CREATION,sap,RECIPE_PRACTICE,…tste doet men 'er een ey klein geklopt met wa...,Method=✓; Process=✗; Product=✓,COOKING_CREATION_Method=''; COOKING_CREATION_P...,COOKING_CREATION_Method=''; COOKING_CREATION_P...,_vol002volm01_01.xml__ch18__v_trekken__sap
4,partial_strong,yes,2,3,PRESERVING,PRESERVING,schol,RECIPE_PRACTICE,"neemt schol, maakt ze schoon, snyd 'er de vinn...",Technique=✓; Medium=✓; Patient=✗,PR_Technique='droogen'; PR_Medium=''; PR_Food_...,PR_Technique='droogen'; PR_Medium=''; PR_Food_...,preservare_2051__drying__schol
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,miss,,0,3,PRESERVING,COOKING_CREATION,snoek,RECIPE_PRACTICE,"snijdse in stukken, strooyt'er zouten ziedend ...",Technique=✗; Medium=✗; Patient=✗,PR_Technique='kooken'; PR_Medium='azijn. water...,"COOKING_CREATION_Method=""snijdse in stukken, s...",preservare_4338__salting__snoek
89,miss,,0,3,PRESERVING,COOKING_CREATION,snoek,RECIPE_PRACTICE,"schrapt, ontweyd, wastse, en brengt de kop en ...",Technique=✗; Medium=✗; Patient=✗,PR_Technique='kooken'; PR_Medium='water'; PR_F...,"COOKING_CREATION_Method='kooktse in water, zou...",preservare_4336__salting__snoek
90,miss,,0,3,PRESERVING,COOKING_CREATION,soep,RECIPE_PRACTICE,"…af, edat het dik in de pot blyve; doe de soup...",Technique=✗; Medium=✗; Patient=✗,PR_Technique='gisten'; PR_Medium='licht'; PR_F...,COOKING_CREATION_Method='dik in de pot blyve';...,preservare_3181__fermentation__soep
91,miss,,0,3,PRESERVING,COOKING_CREATION,vet,RECIPE_PRACTICE,"…n, hoe men die voor de winter zal inzouten. D...",Technique=✗; Medium=✗; Patient=✗,PR_Technique='soucing'; PR_Medium='salt'; PR_F...,COOKING_CREATION_Method='kookt ze een welletje...,_vol002volm01_01.xml__ch17__vet
92,miss,,0,3,PRESERVING,COOKING_CREATION,worst,RECIPE_PRACTICE,"…t het in varkens-darmen, zoo lang als u doenl...",Technique=✗; Medium=✗; Patient=✗,PR_Technique='droogen'; PR_Medium=''; PR_Food_...,COOKING_CREATION_Method='braaden'; COOKING_CRE...,preservare_3604__drying__worst

## Read rows in detail (gold vs pred)

Step through with `start` / `n`. Longer predictions are often fine — exact-match scores understate quality when pred ⊃ gold.

In [5]:
walk_details(slice_, start=0, n=5)
# walk_details(slice_, start=5, n=5)  # next page

=== row 1/93 · partial_strong · Kruidnagelen ===
record_id: chom003huis01_01.xml__ch6__kruidnagelen
frame gold/pred: COOKING_CREATION / COOKING_CREATION  (B: COOKING_CREATION→COOKING_CREATION)
hits: 2/3  field_hits: Method=✗; Process=✓; Product=✓
snippet: …oral eer ze op den Rooster gelegt worden, met eenige Kruidnagelen, en Lauwrierbladen besteken; en ze vervolgens met een zoete zaus opdissen. cardiaca. Deze Plant, ook Hert…
GOLD: COOKING_CREATION_Method='besteken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product=''
PRED: COOKING_CREATION_Method='sneeden, met eenige kruidnagelen, en lauwrierbladen besteken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product=''
fewshot_candidate: 'yes'

=== row 2/93 · partial_strong · Speenvarken ===
record_id: _vol002volm01_01.xml__ch19__speenvarken
frame gold/pred: COOKING_CREATION / COOKING_CREATION  (B: COOKING_CREATION→COOKING_CREATION)
hits: 2/3  field_hits: Method=✓; Process=✓; Product=✗
snippet: …n heeft het geen zwarigheid: Ook moet men nooit geen Speenvarken braden, dan het geen nog zuigt, dog bequaam is om gespeent te worden; want zo het eenige daagen reets nie…
GOLD: COOKING_CREATION_Method='braden'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product=''
PRED: COOKING_CREATION_Method='braden'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='speenvarken'
fewshot_candidate: 'yes'

=== row 3/93 · partial_strong · roosemarijn ===
record_id: magi007kooc02_01.xml__ch10__roosemarijn
frame gold/pred: COOKING_CREATION / COOKING_CREATION  (B: COOKING_CREATION→COOKING_CREATION)
hits: 2/3  field_hits: Method=✗; Process=✓; Product=✓
snippet: …n den spit doen in eenen anderen pot, ende nemen den roosemarijn ende het speck wech, doetter by het vet datter soude moghen afghebraden wesen met wat malvesey oft spaens…
GOLD: COOKING_CREATION_Method='wegnemen'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product=''
PRED: COOKING_CREATION_Method='doetter by het vet datter soude moghen afghebraden wesen met wat malvesey oft spaenschen wijn'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product=''
fewshot_candidate: 'yes'

=== row 4/93 · partial_strong · sap ===
record_id: _vol002volm01_01.xml__ch18__v_trekken__sap
frame gold/pred: COOKING_CREATION / COOKING_CREATION  (B: COOKING_CREATION→COOKING_CREATION)
hits: 2/3  field_hits: Method=✓; Process=✗; Product=✓
snippet: …tste doet men 'er een ey klein geklopt met wat Limoensap onder, dan schud men het door een, en men laat het een quartier braaf door stooven. Op dezelve wyze kan m…
GOLD: COOKING_CREATION_Method=''; COOKING_CREATION_Process='opkoken'; COOKING_CREATION_Food_Product=''
PRED: COOKING_CREATION_Method=''; COOKING_CREATION_Process='stooven'; COOKING_CREATION_Food_Product=''
fewshot_candidate: 'yes'

=== row 5/93 · partial_strong · schol ===
record_id: preservare_2051__drying__schol
frame gold/pred: PRESERVING / PRESERVING  (B: PRESERVING→PRESERVING)
hits: 2/3  field_hits: Technique=✓; Medium=✓; Patient=✗
snippet: neemt schol, maakt ze schoon, snyd 'er de vinnen af, en doet 'er al het ingewand uit, en hangt ze wat op om te drooge…
GOLD: PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='vis'
PRED: PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='schol'
fewshot_candidate: 'yes'

## Few-shot shortlist + save

In [6]:
FEWSHOT = replace(
    CONFIG,
    fewshot_only=True,
    # frames=('COOKING_CREATION',),
    output_path=EVAL / 'step_c_fewshot_candidates.csv',
)
few = load_review_frame(FEWSHOT)
print(review_summary(few))
walk_details(few, start=0, n=10)

path_all = save_review_frame(review, CONFIG)
path_few = save_review_frame(few, FEWSHOT)
print('all →', path_all)
print('fewshot →', path_few)

{'rows': 16, 'tiers': {'partial': 10, 'partial_strong': 6}, 'fewshot_flagged': 16, 'by_frame': {'COOKING_CREATION': 14, 'PRESERVING': 2}}
=== row 1/16 · partial_strong · Kruidnagelen ===
record_id: chom003huis01_01.xml__ch6__kruidnagelen
frame gold/pred: COOKING_CREATION / COOKING_CREATION  (B: COOKING_CREATION→COOKING_CREATION)
hits: 2/3  field_hits: Method=✗; Process=✓; Product=✓
snippet: …oral eer ze op den Rooster gelegt worden, met eenige Kruidnagelen, en Lauwrierbladen besteken; en ze vervolgens met een zoete zaus opdissen. cardiaca. Deze Plant, ook Hert…
GOLD: COOKING_CREATION_Method='besteken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product=''
PRED: COOKING_CREATION_Method='sneeden, met eenige kruidnagelen, en lauwrierbladen besteken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product=''
fewshot_candidate: 'yes'

=== row 2/16 · partial_strong · Speenvarken ===
record_id: _vol002volm01_01.xml__ch19__speenvarken
frame gold/pred: COOKING_CREATION / COOKING_CREATION  (B: COOKING_CREATION→COOKING_CREATION)
hits: 2/3  field_hits: Method=✓; Process=✓; Product=✗
snippet: …n heeft het geen zwarigheid: Ook moet men nooit geen Speenvarken braden, dan het geen nog zuigt, dog bequaam is om gespeent te worden; want zo het eenige daagen reets nie…
GOLD: COOKING_CREATION_Method='braden'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product=''
PRED: COOKING_CREATION_Method='braden'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='speenvarken'
fewshot_candidate: 'yes'

=== row 3/16 · partial_strong · roosemarijn ===
record_id: magi007kooc02_01.xml__ch10__roosemarijn
frame gold/pred: COOKING_CREATION / COOKING_CREATION  (B: COOKING_CREATION→COOKING_CREATION)
hits: 2/3  field_hits: Method=✗; Process=✓; Product=✓
snippet: …n den spit doen in eenen anderen pot, ende nemen den roosemarijn ende het speck wech, doetter by het vet datter soude moghen afghebraden wesen met wat malvesey oft spaens…
GOLD: COOKING_CREATION_Method='wegnemen'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product=''
PRED: COOKING_CREATION_Method='doetter by het vet datter soude moghen afghebraden wesen met wat malvesey oft spaenschen wijn'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product=''
fewshot_candidate: 'yes'

=== row 4/16 · partial_strong · sap ===
record_id: _vol002volm01_01.xml__ch18__v_trekken__sap
frame gold/pred: COOKING_CREATION / COOKING_CREATION  (B: COOKING_CREATION→COOKING_CREATION)
hits: 2/3  field_hits: Method=✓; Process=✗; Product=✓
snippet: …tste doet men 'er een ey klein geklopt met wat Limoensap onder, dan schud men het door een, en men laat het een quartier braaf door stooven. Op dezelve wyze kan m…
GOLD: COOKING_CREATION_Method=''; COOKING_CREATION_Process='opkoken'; COOKING_CREATION_Food_Product=''
PRED: COOKING_CREATION_Method=''; COOKING_CREATION_Process='stooven'; COOKING_CREATION_Food_Product=''
fewshot_candidate: 'yes'

=== row 5/16 · partial_strong · schol ===
record_id: preservare_2051__drying__schol
frame gold/pred: PRESERVING / PRESERVING  (B: PRESERVING→PRESERVING)
hits: 2/3  field_hits: Technique=✓; Medium=✓; Patient=✗
snippet: neemt schol, maakt ze schoon, snyd 'er de vinnen af, en doet 'er al het ingewand uit, en hangt ze wat op om te drooge…
GOLD: PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='vis'
PRED: PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='schol'
fewshot_candidate: 'yes'

=== row 6/16 · partial_strong · tuinboon ===
record_id: preservare_2415__drying__tuinboon
frame gold/pred: PRESERVING / PRESERVING  (B: PRESERVING→PRESERVING)
hits: 2/3  field_hits: Technique=✗; Medium=✓; Patient=✓
snippet: …n welletje in regenwater opkooken: zet ze dan op een vergiettest te verzygen: dan legt men ze op tafels, op zolder, digt aan het venster te droogen; dog men mo…
GOLD: PR_Technique='droogen'; PR_Medium=''; PR_Food_Patient='tuinboon'
PRED: PR_Technique='droogen op tafels, op zolder, digt aan het venster te droogen, op glazen te droogen'; PR_Medium=''; PR_Food_Patient='tuinboon'
fewshot_candidate: 'yes'

=== row 7/16 · partial · Artischokken ===
record_id: chom003huis01_01.xml__ch4__artischokken
frame gold/pred: COOKING_CREATION / COOKING_CREATION  (B: COOKING_CREATION→COOKING_CREATION)
hits: 1/3  field_hits: Method=✗; Process=✓; Product=✗
snippet: …op, die vry zyn van de vorst. Verscheide wyzen om de Artischokken klaar te maken. Artischokken met een zuure Peper-saus. Neemt teêre en malsche Artischokken, snyd ze in vi…
GOLD: COOKING_CREATION_Method='klaarmaken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product=''
PRED: COOKING_CREATION_Method='snyd ze in vierendeels'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='artischokken'
fewshot_candidate: 'maybe'

=== row 8/16 · partial · Kruidnagelen ===
record_id: _vol002volm01_01.xml__ch13__kruidnagelen
frame gold/pred: COOKING_CREATION / COOKING_CREATION  (B: COOKING_CREATION→COOKING_CREATION)
hits: 1/3  field_hits: Method=✗; Process=✗; Product=✓
snippet: … kapt het fyn, en doet 'er zout, peper, Notemuscaat, Kruidnagelen, Champignons, morilles, booter, en zo het in den tyd is, oesters by; legt dit te samen op de onderkorst, …
GOLD: COOKING_CREATION_Method='bakken'; COOKING_CREATION_Process='bakken'; COOKING_CREATION_Food_Product=''
PRED: COOKING_CREATION_Method="doet 'er de graaten schoon uit, en het vel 'er ter degen af; kapt het fyn, en doet 'er zout, peper, notemuscaat, kruidnagelen, champignons, morilles, booter, en zo het in den tyd is, oesters by"; COOKING_CREATION_Process='opkooken zonder zout, zo, dat de vis van de graad los wil laaten'; COOKING_CREATION_Food_Product=''
fewshot_candidate: 'maybe'

=== row 9/16 · partial · Kruidnagelen ===
record_id: cure_stepc__chom003huis01_01.xml__ch11__kruidnagelen__11771
frame gold/pred: COOKING_CREATION / COOKING_CREATION  (B: COOKING_CREATION→COOKING_CREATION)
hits: 1/3  field_hits: Method=✗; Process=✓; Product=✗
snippet: …; kookt het in Vleeschnat; stooft het wel met Peper, Kruidnagelen, ende een glas Wyn. Gaar gekookt zynde, fruit Bloed of Zweet, en Lever in een Pan met een weinig Meel; me…
GOLD: COOKING_CREATION_Method='stoven'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='ragout van haas'
PRED: COOKING_CREATION_Method='gebraden'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='haas'
fewshot_candidate: 'maybe'

=== row 10/16 · partial · garst ===
record_id: cure_stepc___vol002volm01_01.xml__ch8__garst__78084
frame gold/pred: COOKING_CREATION / COOKING_CREATION  (B: COOKING_CREATION→COOKING_CREATION)
hits: 1/3  field_hits: Method=✗; Process=✓; Product=✗
snippet: … van een Kalfs-schinkel, en men laat 'er wat gepelde garst of kruim van wittebrood daar onder kooken, en doet 'er wat zout, notemuscaat, booter, en gestoote peper b…
GOLD: COOKING_CREATION_Method='maaken'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product='soep'
PRED: COOKING_CREATION_Method='snyd'; COOKING_CREATION_Process=''; COOKING_CREATION_Food_Product=''
fewshot_candidate: 'maybe'

all → /Volumes/Extreme SSD/scratch/trifecta/eval/step_c_review.csv
fewshot → /Volumes/Extreme SSD/scratch/trifecta/eval/step_c_fewshot_candidates.csv

## How to use this

1. `walk_details` — compare GOLD vs PRED side by side.
2. If you prefer longer PRED text, treat exact-match misses as **style**, not necessarily wrong — note for soft scoring later.
3. Pick record_ids for few-shots (or say “all yes”) and wire into Step C prompts.
4. Optional: open the saved CSV in Cursor for search/notes.